### ISSUE TITLE
Universal rendering test does not break even if error is thrown

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#712]
# Bug Report

It seems that the universal should not throw an error test does not fail if we have an error ..
```
 Universal
ERROR TypeError: this._elementRef.nativeElement.getBoundingClientRect is not a function
    at DtEmptyState.../../libs/barista-components/empty-state/src/empty-state.ts.DtEmptyState._updateLayout (/home/circleci/barista/dist/universal/server/main.js:10495:61)
    at SafeSubscriber._next (/home/circleci/barista/dist/universal/server/main.js:10469:23)
    at SafeSubscriber.../../node_modules/rxjs/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (/home/circleci/barista/dist/universal/server/main.js:189586:16)
    at SafeSubscriber.../../node_modules/rxjs/internal/Subscriber.js.SafeSubscriber.next (/home/circleci/barista/dist/universal/server/main.js:189524:22)
    at Subscriber.../../node_modules/rxjs/internal/Subscriber.js.Subscriber._next (/home/circleci/barista/dist/universal/server/main.js:189470:26)
    at Subscriber.../../node_modules/rxjs/internal/Subscriber.js.Subscriber.next (/home/circleci/barista/dist/universal/server/main.js:189447:18)
    at TakeUntilSubscriber.../../node_modules/rxjs/internal/Subscriber.js.Subscriber._next (/home/circleci/barista/dist/universal/server/main.js:189470:26)
    at TakeUntilSubscriber.../../node_modules/rxjs/internal/Subscriber.js.Subscriber.next (/home/circleci/barista/dist/universal/server/main.js:189447:18)
    at MergeMapSubscriber.../../node_modules/rxjs/internal/operators/mergeMap.js.MergeMapSubscriber.notifyNext (/home/circleci/barista/dist/universal/server/main.js:194825:26)
    at InnerSubscriber.../../node_modules/rxjs/internal/InnerSubscriber.js.InnerSubscriber._next (/home/circleci/barista/dist/universal/server/main.js:188664:21)

 ✓ Universal rendering should not throw an error
```

**Comment by ffriedl89** [comment]
After doing a lot of investigating for this issue it seems that nguniversal has an issue there in the the prerender parts. A childprocess is forked that runs the render.js worker. The worker takes the renderModuleFn from the serverBundle and renders the HTML. It seems that the renderModuleFn catches all errors, but logs them to the console. At this point i'd say this is not worth further investment since we strive to remove the universal app as is anyway and use barista for universal rendering in the future.
