### ISSUE TITLE
Barista: Universal renderer throws console error with IconColorWheel

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#798]
# Bug Report

Barista Universal rendering is throwing an error when rendering the icon colour wheel (console error):

![image](https://user-images.githubusercontent.com/11156362/77656576-5cadb980-6f74-11ea-9dea-f3ca5e40fcfd.png)

## Steps to Reproduce

1. `npm run examples-tools`
2. `npm run barista-tools`
3. `ng build workspace`
4. `ng run barista-design-system:render:production`

Nevertheless, the build is working it is throwing the console error. Should be investigated!

if a `ng run barista-design-system:serve-ssr` is performed instead of step 4 and a manual navigation to an icon detail page is performed: `resources/icons/xhrprocess` it throws this error as well.

```
ERROR Error: NotYetImplemented
    at Element.XFB9.exports.nyi (/Users/lukas.holzer/Sites/barista/dist/apps/barista-design-system/server/main.js:1:2595009)
    at EmulatedEncapsulationServerRenderer2.DefaultServerRenderer2.setProperty (/Users/lukas.holzer/Sites/barista/dist/apps/barista-design-system/server/main.js:1:2091582)
    at BaseAnimationRenderer.setProperty (/Users/lukas.holzer/Sites/barista/dist/apps/barista-design-system/server/main.js:1:1821057)
    at elementPropertyInternal (/Users/lukas.holzer/Sites/barista/dist/apps/barista-design-system/server/main.js:1:5042408)
    at Object.ɵɵproperty (/Users/lukas.holzer/Sites/barista/dist/apps/barista-design-system/server/main.js:1:5132587)
    at BaIconColorWheel_Template (/Users/lukas.holzer/Sites/barista/dist/apps/barista-design-system/server/main.js:1:909712)
    at executeTemplate (/Users/lukas.holzer/Sites/barista/dist/apps/barista-design-system/server/main.js:1:5036827)
    at refreshView (/Users/lukas.holzer/Sites/barista/dist/apps/barista-design-system/server/main.js:1:5033418)
    at refreshComponent (/Users/lukas.holzer/Sites/barista/dist/apps/barista-design-system/server/main.js:1:5049608)
    at refreshChildComponents (/Users/lukas.holzer/Sites/barista/dist/apps/barista-design-system/server/main.js:1:5035599)
```

**Comment by rowa-audil** [comment]
I cannot reproduce the bug when going over these steps.
Magically fixed??
